# Navigation Links

main:

  - name: À propos
    url: /
    weight: 10

  - name: Expérience
    url: /experience/
    weight: 20

  - name: Projets
    url: /projects/
    weight: 30

  - name: Publications
    url: /publications/
    weight: 40

  - name: Formations
    url: /courses/
    weight: 50
